-- Households: foundation for shared pantry sharing (PR1 of 3).
--
-- This migration is intentionally additive: existing pantry_items, waste_logs,
-- and profiles RLS / queries are untouched, and the application keeps working
-- exactly as it does today. Only the new household tables are introduced.
--
-- Subsequent PRs:
--   PR2: Edge Function (create / join / leave / regenerate invite) + Settings
--        UI for "Family Sharing".
--   PR3: Backfill a personal household for every existing user, flip
--        pantry_items / waste_logs queries to filter by household_id, and
--        wire up multi-writer conflict handling.
--
-- Rollback (manual, if needed):
--   drop table household_members cascade;
--   drop table households cascade;
--   drop function is_household_member(uuid);
--   alter table profiles      drop column household_id;
--   alter table pantry_items  drop column household_id;
--   alter table waste_logs    drop column household_id;

create extension if not exists pgcrypto;

-- ── Tables ──────────────────────────────────────────────────────────────────

create table if not exists households (
  id          uuid primary key default gen_random_uuid(),
  name        text,
  -- Short, human-shareable join code (e.g. "AVO-7K2P"). Generated by the
  -- PR2 Edge Function; uniqueness is enforced here so collisions surface as
  -- insert errors that the function can retry.
  invite_code text not null unique,
  -- Nullable so a creator deleting their account doesn't take the whole
  -- household with them — other members may still be using it. The Edge
  -- Function in PR2 reassigns ownership before the creator can fully leave.
  created_by  uuid references auth.users(id) on delete set null,
  created_at  timestamptz not null default now()
);

create index if not exists households_invite_code_idx on households (invite_code);

create table if not exists household_members (
  household_id uuid not null references households(id) on delete cascade,
  user_id      uuid not null references auth.users(id) on delete cascade,
  role         text not null check (role in ('owner', 'member')),
  joined_at    timestamptz not null default now(),
  primary key (household_id, user_id)
);

-- Each user belongs to at most one household. The product UX is "one family
-- pantry at a time" — when a user joins another household, the PR2 Edge
-- Function removes their old membership first. Enforcing it at the schema
-- level catches bugs that would otherwise silently leak data between groups.
create unique index if not exists household_members_user_unique
  on household_members (user_id);

create index if not exists household_members_household_idx
  on household_members (household_id);

-- ── Household ID on existing tables (NULLABLE) ─────────────────────────────
--
-- Rows where household_id IS NULL stay user-owned (current behaviour). PR3
-- will backfill personal households for every existing user and set this
-- column accordingly, then switch reads/writes over.

alter table profiles      add column if not exists household_id uuid references households(id) on delete set null;
alter table pantry_items  add column if not exists household_id uuid references households(id) on delete set null;
alter table waste_logs    add column if not exists household_id uuid references households(id) on delete set null;

create index if not exists pantry_items_household_id_idx on pantry_items (household_id);
create index if not exists waste_logs_household_id_idx   on waste_logs   (household_id);

-- ── Membership helper ──────────────────────────────────────────────────────
--
-- SECURITY DEFINER lets this read household_members without triggering the
-- members' own RLS policy — required to break the recursion that would
-- otherwise occur when household_select calls into household_members_select
-- which calls into is_household_member, etc.

create or replace function is_household_member(hid uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from household_members
    where household_id = hid
      and user_id = auth.uid()
  );
$$;

create or replace function is_household_owner(hid uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from household_members
    where household_id = hid
      and user_id = auth.uid()
      and role = 'owner'
  );
$$;

-- ── RLS: households ────────────────────────────────────────────────────────

alter table households enable row level security;

drop policy if exists households_select on households;
create policy households_select on households
  for select
  using (is_household_member(id));

-- Anyone authenticated can create a household, as long as the created_by
-- column matches their own user id. They become the first member via the
-- Edge Function (which runs with service-role to insert into
-- household_members below).
drop policy if exists households_insert on households;
create policy households_insert on households
  for insert
  with check (created_by = auth.uid());

drop policy if exists households_update on households;
create policy households_update on households
  for update
  using (is_household_owner(id))
  with check (is_household_owner(id));

drop policy if exists households_delete on households;
create policy households_delete on households
  for delete
  using (is_household_owner(id));

-- ── RLS: household_members ─────────────────────────────────────────────────

alter table household_members enable row level security;

-- Members can see who else is in their household.
drop policy if exists household_members_select on household_members;
create policy household_members_select on household_members
  for select
  using (is_household_member(household_id));

-- Joins are intentionally NOT covered by an INSERT policy. The PR2 Edge
-- Function uses the service role to insert membership rows after validating
-- an invite code — keeping invite-code validation server-side prevents
-- enumeration attacks against the join endpoint.

-- A user can remove themselves (leave); an owner can remove anyone (kick).
drop policy if exists household_members_delete on household_members;
create policy household_members_delete on household_members
  for delete
  using (
    user_id = auth.uid()
    or is_household_owner(household_id)
  );

-- Role changes (promote/demote) go through the Edge Function in PR2.
-- No UPDATE policy = blocked by default.
